name: Client Quality
on:
  workflow_call:

jobs:
  client-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 21
          cache: 'yarn'
      - run: yarn install
      - run: yarn prettier-check
      - run: NODE_OPTIONS="--max-old-space-size=4096" yarn build
      - run: yarn test
