name: Main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  api-quality:
    uses: ./.github/workflows/.api-quality.yml

  client-quality:
    uses: ./.github/workflows/.client-quality.yml

  api-build:
    uses: ./.github/workflows/.build.yml
    with:
      env: staging
      registry_suffix: staging
      app_name: workflowai-api-staging
      service: api
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      SENTRY_HOOK: ${{ secrets.SENTRY_API_HOOK }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  client-build:
    uses: ./.github/workflows/.build.yml
    with:
      env: staging
      registry_suffix: staging
      app_name: workflowai-client-staging
      service: client
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      SENTRY_HOOK: ${{ secrets.SENTRY_CLIENT_HOOK }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      build_args: |
        ENV_NAME=staging
        API_URL=${{ vars.API_URL }}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
        NEXT_PUBLIC_AMPLITUDE_API_KEY=${{ secrets.NEXT_PUBLIC_AMPLITUDE_API_KEY }}
        NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}

  api-deploy-api:
    needs: [api-quality, api-build]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      image_name: ${{ needs.api-build.outputs.image_name }}
      env: staging
      full_app_name: workflowai-api-staging
      # deployment channel id
      channel_id: ${{ secrets.DEPLOY_CHANNEL_ID }}
      app_url: ${{ secrets.APP_URL }}

  api-deploy-worker:
    needs: [api-quality, api-build]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      image_name: ${{ needs.api-build.outputs.image_name }}
      env: staging
      full_app_name: workflowai-worker-staging

  api-deploy-run:
    needs: [api-quality, api-build]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      image_name: ${{ needs.api-build.outputs.image_name }}
      env: staging
      full_app_name: workflowai-run-staging
      label: preview

  api-deploy-run1:
    needs: [api-quality, api-build]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      image_name: ${{ needs.api-build.outputs.image_name }}
      env: staging
      full_app_name: workflowai-run1-staging
      label: preview
