name: Quality
on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      api: ${{ steps.filter.outputs.api }}
      client: ${{ steps.filter.outputs.client }}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          filters: |
            api:
              - 'api/**'
            client:
              - 'client/**'
  api:
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    uses: ./.github/workflows/.api-quality.yml

  client:
    needs: changes
    if: ${{ needs.changes.outputs.client == 'true' }}
    uses: ./.github/workflows/.client-quality.yml
